// Root ESLint configuration focusing on backend Cloudflare functions
export default [
  {
    ignores: [
      "node_modules/**",
      "frontend/**",
      "docs/**",
      "database/**",
      "chatmodes/**",
      "instructions/**",
      "scripts/**",
      "coverage/**",
      "dist/**",
      "public/**",
      ".wrangler/**",
    ],
  },
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        fetch: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        URL: "readonly",
        File: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        structuredClone: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        btoa: "readonly",
        atob: "readonly",
        Buffer: "readonly",
      },
    },
    rules: {
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      eqeqeq: "error",
      "prefer-const": "warn",
      "no-undef": "error",
      // Security best practices
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-unsafe-negation": "error",
      // Code quality
      "no-var": "error",
      "prefer-arrow-callback": "warn",
      "no-throw-literal": "error",
      "prefer-promise-reject-errors": "error",
      // Best practices
      "require-await": "warn",
      "no-async-promise-executor": "error",
    },
  },
  {
    files: ["**/__tests__/**/*.js", "**/*.test.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        vi: "readonly",
      },
    },
  },
];
